version: "3.7"
services:
  php:
    build: './docker/php'
    networks:
      - backend
    volumes:
      - app-src-dir:/var/www/html:delegated
      - ${PWD}/docker/php/configs/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${PWD}/docker/php/configs/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  apache:
    build: './docker/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    extra_hosts:
      - '${APACHE_HOSTNAME}:127.0.0.1'
    ports:
      - "8080:80"
      # make virtualhost available without :8080
      - "80:80"
      - "443:443"
    volumes:
      - app-src-dir:/var/www/html:delegated
      # mount non-SSL .htaccess
      # - ./docker/apache/.htaccess:/var/www/html/.htaccess
    # from .env
    environment:
      - HOSTNAME=${APACHE_HOSTNAME}

  mysql:
    image: "mysql:5.7"
    networks:
      - backend
    ports:
      - "3306:3306"
    # allow zero-formatted dates for installation
    command: mysqld --sql_mode=""
    # from .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DEV_NAME}
      - MYSQL_PASSWORD=${MYSQL_DEV_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DEV_ROOT_PASS}
      - MYSQL_USER=${MYSQL_DEV_USER}

  mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      - backend
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  backend:
  frontend:

volumes:
  app-src-dir:
    driver_opts:
      type: none
      # use ./src as the volume's host source directory
      device: "$PWD/src"
      o: bind
